import { describe, it, expect, beforeAll, beforeEach, afterAll, vi } from 'vitest'
import type { FastifyInstance } from 'fastify'
import { buildApp } from '../../helpers/app'
import { cleanDb, createUser, createChild } from '../../fixtures/index'
import { prisma } from '../../../db/client'

// ── LLM mock ──────────────────────────────────────────────────────────────────

const mockGenerateExportContent = vi.hoisted(() => vi.fn())

vi.mock('../../../llm/anthropic', () => ({
  extractSignals: vi.fn(),
  personalizeCards: vi.fn(),
  generateExportContent: mockGenerateExportContent,
  parseIEPDocument: vi.fn(),
}))

// Default mock returns HTML with disclaimer text
const defaultExportHtml = `
<h1>Teacher Quick-Reference</h1>
<p>Alex benefits from structured peer interaction.</p>
<div class="footer">Generated by myautismguidance — based on caregiver observation. Not a clinical assessment.</div>
`

// ── Test suite ────────────────────────────────────────────────────────────────

describe('POST /api/children/:id/exports', () => {
  let app: FastifyInstance
  let userId: string
  let childId: string

  beforeAll(async () => {
    app = buildApp()
    await app.ready()
  })

  afterAll(async () => {
    await app.close()
  })

  beforeEach(async () => {
    await cleanDb()
    mockGenerateExportContent.mockResolvedValue(defaultExportHtml)
    const user = await createUser()
    userId = user.id
    const child = await createChild(userId)
    childId = child.id
  })

  it('returns HTTP 200 with ExportRecord data and downloadUrl', async () => {
    const response = await app.inject({
      method: 'POST',
      url: `/api/children/${childId}/exports`,
      payload: { exportType: 'teacher-card', depth: 'summary' },
    })
    expect(response.statusCode).toBe(200)
    const body = response.json()
    expect(body.id).toBeDefined()
    expect(body.exportType).toBe('teacher-card')
    expect(body.depthMode).toBe('summary')
    expect(body.downloadUrl).toBeDefined()
    expect(body.downloadUrl).toContain('/api/exports/')
  })

  it('creates ExportRecord in DB', async () => {
    const response = await app.inject({
      method: 'POST',
      url: `/api/children/${childId}/exports`,
      payload: { exportType: 'teacher-card', depth: 'summary' },
    })
    const body = response.json()
    const record = await prisma.exportRecord.findUnique({ where: { id: body.id } })
    expect(record).not.toBeNull()
    expect(record!.exportType).toBe('teacher-card')
    expect(record!.childId).toBe(childId)
  })

  it('returns HTTP 404 when child not found', async () => {
    const response = await app.inject({
      method: 'POST',
      url: '/api/children/nonexistent-child-id/exports',
      payload: { exportType: 'teacher-card' },
    })
    expect(response.statusCode).toBe(404)
  })
})

describe('GET /api/exports/:id/download', () => {
  let app: FastifyInstance
  let userId: string
  let childId: string

  beforeAll(async () => {
    app = buildApp()
    await app.ready()
  })

  afterAll(async () => {
    await app.close()
  })

  beforeEach(async () => {
    await cleanDb()
    mockGenerateExportContent.mockResolvedValue(defaultExportHtml)
    const user = await createUser()
    userId = user.id
    const child = await createChild(userId)
    childId = child.id
  })

  it('returns HTML content with disclaimer footer "Not a clinical assessment."', async () => {
    // First generate an export to get an ID
    const createResponse = await app.inject({
      method: 'POST',
      url: `/api/children/${childId}/exports`,
      payload: { exportType: 'teacher-card', depth: 'summary' },
    })
    expect(createResponse.statusCode).toBe(200)
    const { id } = createResponse.json()

    // Download the generated export
    const response = await app.inject({
      method: 'GET',
      url: `/api/exports/${id}/download`,
    })
    expect(response.statusCode).toBe(200)
    expect(response.headers['content-type']).toContain('text/html')
    expect(response.body).toContain('Not a clinical assessment.')
  })

  it('returns HTTP 404 for unknown export ID', async () => {
    const response = await app.inject({
      method: 'GET',
      url: '/api/exports/nonexistent-export-id/download',
    })
    expect(response.statusCode).toBe(404)
  })
})
